src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from .views import index_view

urlpatterns = [
    path("", index_view, name="index"),
    path("notecards/", include("notecards.urls", namespace="notecards")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

src/notecards/urls.py
from django.urls import path

from .views import (
    NotecardDetailView,
    NotecardListView,
    index,
    notecard_create,
    notecard_delete,
    notecard_update,
)

app_name = "notecards"

urlpatterns = [
    path("", index, name="index"),
    path("list/", NotecardListView.as_view(), name="list"),
    path(
        "detail/<int:pk>/",
        NotecardDetailView.as_view(),
        name="detail",
    ),
    path("create/", notecard_create, name="create"),
    path("update/<int:pk>/", notecard_update, name="update"),
    path("delete/<int:pk>/", notecard_delete, name="delete"),
]

src/notecards/models.py
from django.db import models
from django.urls import reverse_lazy


class Notecard(models.Model):
    title = models.CharField(max_length=50, unique=True)
    content = models.TextField(blank=True, max_length=200)

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("notecards:detail", kwargs={"pk": self.pk})

src/notecards/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout
from django import forms
from django.core.exceptions import ValidationError

from core.settings import MAX_RECORDS

from .models import Notecard


class NoteForm(forms.ModelForm):
    class Meta:
        model = Notecard
        fields = ["title", "content"]

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "maxlength": "50",
            }
        )
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(NoteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Field("title", wrapper_class="col-sm-12"),
                css_class="row",
            ),
            Div(
                Field("content", wrapper_class="col-sm-12"),
                css_class="row",
            ),
        )

    def clean(self):
        cleaned_data = super(NoteForm, self).clean()
        title = cleaned_data.get("title")
        if (
            not Notecard.objects.filter(title=title).exists()
            and Notecard.objects.count() >= MAX_RECORDS
        ):
            raise ValidationError(
                f"Maximum limit of {MAX_RECORDS} notecards reached. Please delete a notecard."
            )
        return cleaned_data

src/core/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods


@require_http_methods(["GET"])
def index_view(request):
    msg = "Welcome to the Notecards app."

    context = {"msg": msg}
    return render(request, "index.html", context)

src/notecards/views.py
import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, ListView

from notecards.models import Notecard

from .forms import NoteForm


@require_http_methods(["GET"])
def index(request):
    return render(request, "notecards/index.html")


class NotecardListView(ListView):
    http_method_names = ["get"]
    model = Notecard
    template_name = "notecards/partials/notecard_list.html"


class NotecardDetailView(DetailView):
    http_method_names = ["get"]
    model = Notecard
    template_name = "notecards/partials/notecard_detail.html"


@require_http_methods(["GET", "POST"])
def notecard_create(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            notecard = form.save()
            return HttpResponse(
                status=204,
                headers={
                    "HX-Trigger": json.dumps(
                        {
                            "update_notecard_list": None,
                            "showMessage": f'Notecard "{notecard.title}" added.',
                        }
                    )
                },
            )
    else:
        form = NoteForm()

    template_name = "notecards/partials/notecard_form.html"
    context = {
        "form": form,
    }
    return render(request, template_name, context)


@require_http_methods(["GET", "POST"])
def notecard_update(request, pk):
    notecard = get_object_or_404(Notecard, pk=pk)
    if request.method == "POST":
        form = NoteForm(request.POST, instance=notecard)
        if form.is_valid():
            notecard = form.save()
            return HttpResponse(
                status=204,
                headers={
                    "HX-Trigger": json.dumps(
                        {
                            "update_notecard_list": None,
                            "showMessage": f'Notecard "{notecard.title}" updated.',
                        }
                    )
                },
            )
    else:
        form = NoteForm(instance=notecard)
    template_name = "notecards/partials/notecard_form.html"
    context = {"form": form, "notecard": notecard}
    return render(request, template_name, context)


@require_http_methods(["DELETE"])
def notecard_delete(request, pk):
    notecard = get_object_or_404(Notecard, pk=pk)
    notecard.delete()
    return HttpResponse(
        status=204,
        headers={
            "HX-Trigger": json.dumps(
                {
                    "update_notecard_list": None,
                    "showMessage": f'Notecard "{notecard.title}" deleted.',
                }
            )
        },
    )

src/notecards/templates/notecards/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n bootstrap5 %}
{% block head_title %}Notecards{% endblock head_title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div id="messages" hx-get="{% url 'notecards:get_messages' }" hx-target="this" hx-trigger="update_messages from:body">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="container-fluid my-4 col-8">
        <button hx-get="{% url 'notecards:create' %}" hx-target="#notesModal" class="btn btn-primary">Create notecard</button>
      </div>
    </div>
    <div class="row">
      <div class="container-fluid my-4 col-8">
        <div id="notecards-list-group" hx-trigger="load, update_notecard_list from:body" hx-get="{% url 'notecards:list' %}" hx-target="this" class="list-group">
          <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal fade">
    <div id="notesModal" class="modal-dialog" hx-target="this"></div>
  </div>

  <!-- Placeholder for toast -->
  <div class="toast-container position-fixed top-0 mt-1 start-50 translate-middle-x">
    <div id="toast" class="toast align-items-center text-white bg-info border-0" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div id="toast-body" class="toast-body"></div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  </div>

{% endblock content %}
{% block js %}
  <!-- Add CSRF tokent to header -->
  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
  </script>
{% endblock js %}

src/notecards/templates/notecards/partials/notecard_detail.html
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">
      <div class="card bg-secondary">
        <div class="card-header text-primary"><strong>{{ notecard.title }}</strong>
            <button type="button" class="btn btn-sm btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="card-body">
          <p class="card-text">{{ notecard.content }}</p>
        </div>
      </div>
    </div>
  </div>

src/notecards/templates/notecards/partials/notecard_form.html
{% load crispy_forms_tags %}
  <form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Create notecard</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {% crispy form %}
    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-primary">Save</button>
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
        Cancel
      </button>
    </div>
  </form>

src/notecards/templates/notecards/partials/notecard_item.html
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a hx-get="{% url 'notecards:detail' notecard.pk %}" hx-target="#notesModal" class="btn btn-outline-primary">
      {{ notecard.title }}
    </a>
    <div class="float-end">
      <a href="" class="btn btn-primary btn-sm" hx-target="#notesModal" hx-get="{% url 'notecards:update' pk=notecard.pk %}"><i class="bi bi-pencil-square"></i></a>
      <a href="" class="btn btn-danger btn-sm" hx-confirm="Are you sure you wish to delete this notecard?" hx-delete="{% url 'notecards:delete' pk=notecard.pk %}"><i class="bi bi-trash"></i></a>
    </div>
  </li>

src/notecards/templates/notecards/partials/notecard_list.html
  <ul class="list-group">
    {% if notecard_list %}
    {% for notecard in notecard_list %}
      {% include "notecards/partials/notecard_item.html" %}
    {% endfor %}
    {% else %}
    <div id="notecards-list-group" class="list-group-item">
    No notecards created.
    </div>
    {% endif %}
  </ul>

src/templates/base.html
{% load static %}
{% load i18n bootstrap5 %}
{% load django_htmx %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Will">
    <meta name="keywords" content="django, htmx">
    <meta name="description" content="Django HTMX demo app">
    <title>{% block head_title %}Django htmx demo{% endblock head_title %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    {% block headcontent %}{% endblock %}
  </head>
  <body>
    {% include 'partials/navbar.html' %}
    {% block content %}{% endblock content %}
    <!-- bootstrap js bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
    <!-- htmx -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.7.0/htmx.min.js"
      integrity="sha512-etqA0KankuxrlSeZDYycQBY/D/KWZn0YZjlsjAo7kCEBTy1gg+DwmR6icxtOpqDBOzm2P00/lSIXEu7K+zvNsg=="
      crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- custom js -->
    <script src="{% static 'js/main.js' %}"></script>
    {% block js %}{% endblock js %}
    {% django_htmx_script %}
  </body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="p-3 mt-4 mb-5 bg-secondary bg-gradient rounded-3">
      <div class="container-fluid py-5 text-white">
          <h1 class="display-5 fw-bold">{{ msg }}</h1>
      </div>
    </div>
  </div>
{% endblock content %}

src/templates/partials/navbar.html
{% load static %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}" title="Notes">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link px-3" href="{% url 'notecards:index' %}">Notecards</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item mx-5">
        </li>
      </ul>
      </div>
    </div>
  </nav>